# Generated by Django 4.0.5 on 2022-07-05 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ratings',
            field=models.ManyToManyField(related_name='ratings', through='course.Rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
