# Generated by Django 4.0.5 on 2022-07-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_courseview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseview',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
