# Generated by Django 4.0.5 on 2022-07-05 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_courseview_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseview',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='course.course'),
        ),
    ]
