# Generated by Django 4.0.5 on 2022-07-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_courseview_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseview',
            old_name='views',
            new_name='view',
        ),
    ]
