# Generated by Django 4.0.5 on 2022-07-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_views_courseview_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='point',
            new_name='rating',
        ),
    ]
