# Generated by Django 4.0.5 on 2022-08-02 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='code',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='token',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 16, 59, 58, 360935)),
        ),
    ]
