# Generated by Django 4.1 on 2022-08-12 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_token_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 6, 18, 42, 444635, tzinfo=datetime.timezone.utc)),
        ),
    ]
